<?php
/**
 * Created by PhpStorm.
 * User: suleymantopaloglu
 * Date: 23.10.18
 * Time: 09:37
 */

namespace _list;
use Controller;
use REPOSITORY;

class Contact extends Controller
{

        public function index()
        {
                // TODO: Implement index() method.
        }




        function fetchAll(){

                $this->model->pars = $this->pars;
                return $this->model->{__FUNCTION__}();

        }

        function save(){

                // highlight_string(var_export($this->pars, true));
                // return false;
                $this->model->pars = $this->pars;
                $process = $this->model->{__FUNCTION__}();
                // highlight_string(var_export($process->query, true));
                
                if( $process->resulta ){

                        // Overwrite User Data to Repository
                        // highlight_string(var_export($process->userData, true));
                        REPOSITORY::write(REPOSITORY::CURRENT_USER, array_shift($process->userData ) );

                        if( $process->process ){
                                $message = "Wurde erfolgreich gespeichert!";
                                $color = "success";

                        } else {
                                $message = "Alles klar!";
                                $color = "warning";
                        }

                } else {
                        $message = $process->errInfo;
                        $color = "danger";

                }

                return (object) array( "resulta"=>$process->resulta, "process"=>$process->process, "message"=>$message, "color"=>$color ) ;
        }


        public function __construct($pars)
        {
                try {
                        parent::__construct($pars);
                } catch (\ReflectionException $e) {
                }
        }


        public function __destruct()
        {
                parent::__destruct(); // TODO: Change the autogenerated stub
        }
}