<?php
/**
 * Created by PhpStorm.
 * User: suleymantopaloglu
 * Date: 05.02.19
 * Time: 14:16
 * Terms And Conditions
 */

namespace gtc;
use Controller;
use FETCH_STRUCTURE;

class Gtc extends \Controller
{

        public function __construct($pars)
        {
                parent::__construct($pars);
        }




        public function index()
        {
                // TODO: Implement index() method.


                $this->view->setPostDataStructure(FETCH_STRUCTURE::FETCH_OBJECT);
                $this->view->pars = array(


                );

                $this->view->render($this->getReflectedClass()->getShortName(), $this->getReflectedClass()->getNamespaceName() . DIRECTORY_SEPARATOR . __FUNCTION__ );


        }


        public function __destruct()
        {
                parent::__destruct(); // TODO: Change the autogenerated stub
        }

}

namespace terms;
use Controller;

class Gtc extends \Controller
{

        public function __construct($pars)
        {
                parent::__construct($pars);
        }




        public function index()
        {
                // TODO: Implement index() method.
        }


        public function __destruct()
        {
                parent::__destruct(); // TODO: Change the autogenerated stub
        }

}

namespace conditions;
use Controller;

class Gtc extends \Controller
{

        public function __construct($pars)
        {
                parent::__construct($pars);
        }




        public function index()
        {
                // TODO: Implement index() method.
        }


        public function __destruct()
        {
                parent::__destruct(); // TODO: Change the autogenerated stub
        }

}