<?php
/**
 * Created by PhpStorm.
 * User: suleymantopaloglu
 * Date: 31.01.19
 * Time: 13:37
 * Sample Controller Use Static and Dynamic Menu
 */

class Sample extends Controller
{

        public function __construct($pars, $public_load)
        {
                parent::__construct($pars, $public_load);
        }

        function __destruct()
        {
                parent::__destruct(); // TODO: Change the autogenerated stub
        }

        public function index()
        {
                // TODO: Implement index() method.
                $this->view->setPostDataStructure(FETCH_STRUCTURE::FETCH_OBJECT);
                $this->view->data = array(
                        "view"=>"Sample View"
                );

                $this->view->render($this->getReflectedClass()->getShortName(), __FUNCTION__);

        }
}