<?php
/**
 * Created by PhpStorm.
 * User: suleymantopaloglu
 * Date: 16.02.19
 * Time: 04:00
 */

namespace tableView;
use Controller;
use ReflectionException;
use FETCH_STRUCTURE;
class Test extends Controller
{
        /**
         * Test constructor.
         * @param $pars
         * @throws ReflectionException
         */
        public function __construct($pars)
        {
                parent::__construct($pars);
        }

        function __destruct()
        {
                parent::__destruct(); // TODO: Change the autogenerated stub
        }


        public function index()
        {
                // TODO: Implement index() method.

                // echo $this->pars->role;
                $roles = $this->public->getRoles();

                $this->view->setPostDataStructure(FETCH_STRUCTURE::FETCH_OBJECT);
                $this->view->data = array(
                    "roles"=>$roles
                );

                $this->view->render($this->getReflectedClass()->getShortName(), $this->getReflectedClass()->getNamespaceName() . DIRECTORY_SEPARATOR . __FUNCTION__ );
        }


        public function test(){

                return $this->pars->data;

        }


}