<?php
/**
 * Created by PhpStorm.
 * User: suleymantopaloglu
 * Date: 09.12.18
 * Time: 21:44
 */

namespace _start;
use Model;
class Extras_Model extends Model{

        function __construct()
        {
                parent::__construct();
        }

        function __destruct()
        {
                parent::__destruct(); // TODO: Change the autogenerated stub
        }

        public function connect()
        {
                parent::connect(); // TODO: Change the autogenerated stub
        }



}

namespace _teams;
use Model;
class Extras_Model extends Model{

        function __construct()
        {
                parent::__construct();
        }

        function __destruct()
        {
                parent::__destruct(); // TODO: Change the autogenerated stub
        }

        public function connect()
        {
                parent::connect(); // TODO: Change the autogenerated stub
        }

        public function fetchTeams(){

                include "Models/Team_Model.php";
                $team_model = new Team_Model();
                $team_model->pars = $this->pars;
                #highlight_string(var_export($this->pars, true));
                return $team_model->{__FUNCTION__}();

        }



}

namespace _overview;
use _team\Team_Model;
use Model;
class Extras_Model extends Model
{

        /**
         * Extras_Model constructor.
         */
        public function __construct()
        {
                parent::__construct();
        }

        public function __destruct()
        {
                // TODO: Implement __destruct() method.
        }

        public function connect()
        {
                parent::connect(); // TODO: Change the autogenerated stub
        }


        public function fetchTeam(){


                include "Models/Team_Model.php";
                $team_model = new Team_Model();
                $team_model->pars = $this->pars;
                $team = $team_model->{__FUNCTION__}();
                return $team;

        }



}

namespace _table;
use _team\Team_Model;
use Model;
class Extras_Model extends Model
{

        /**
         * Extras_Model constructor.
         */
        public function __construct()
        {
                parent::__construct();
        }

        public function __destruct()
        {
                // TODO: Implement __destruct() method.
        }

        public function connect()
        {
                parent::connect(); // TODO: Change the autogenerated stub
        }


        public function fetchTeam(){


                include "Models/Team_Model.php";
                $team_model = new Team_Model();
                $team_model->pars = $this->pars;
                $team = $team_model->{__FUNCTION__}();
                return $team;

        }
}

namespace _document;
use Model;
use Database;
use Config;
class Extras_Model extends Model{

        public function __construct()
        {
                parent::__construct();
        }
        public function __destruct()
        {
                parent::__destruct(); // TODO: Change the autogenerated stub
        }

        public function connect()
        {
                parent::connect(); // TODO: Change the autogenerated stub
        }


        function  fetchGroups(){




                $sql = "SELECT * FROM " . Config::DB_Name . ".mannschaft_docs WHERE mannschaft_id=" . $this->pars->teams;

                $this->db = new Database();
                $this->db->setQuery($sql);
                $data = $this->db->fetch();
                return array(
                  "resulta"=>$this->db->resulta,
                  "process"=>$this->db->process,
                  "data"=>$data,
                  "sql"=>$this->db->getQueryString(),
                  "errInfo"=>$this->db->errInfo,
                  "errCode"=>$this->db->errCode
                );

        }


        function  fetchGroupDocs(){


                $sql = "SELECT *,
                (SELECT club_id FROM " . Config::DB_Name . ".mannschaft WHERE mannschaft.id=mannschaft_id) as club_id
                FROM " . Config::DB_Name . ".mannschaft_docs WHERE id=" . $this->pars->group_id;

                // (SELECT CONCAT('" . Config::CLUB_DOCS_BASE_URI . "', '/' ,club_id, '/members/', member_image_formatted_name ,'.png')) as file_url
                $this->db = new Database();
                $this->db->setQuery($sql);
                $data = $this->db->fetch();
                return array(
                        "resulta"=>$this->db->resulta,
                        "process"=>$this->db->process,
                        "data"=>$data,
                        "sql"=>$this->db->getQueryString(),
                        "errInfo"=>$this->db->errInfo,
                        "errCode"=>$this->db->errCode
                );

        }

}






// DEPRECATED HERE USE IN TABLE VIEW


namespace _season;
use Model;
use Database;
use Config;
class Extras_Model extends Model{

        public function __construct()
        {
                parent::__construct();
        }
        public function __destruct()
        {
                parent::__destruct(); // TODO: Change the autogenerated stub
        }

        public function connect()
        {
                parent::connect(); // TODO: Change the autogenerated stub
        }

}

namespace _leagues;
use Model;
use Database;
use Config;
class Extras_Model extends Model{

        public function __construct()
        {
                parent::__construct();
        }
        public function __destruct()
        {
                parent::__destruct(); // TODO: Change the autogenerated stub
        }

        public function connect()
        {
                parent::connect(); // TODO: Change the autogenerated stub
        }

}

namespace _postcodes;
use Model;
class Extras_Model extends Model{

        public function __construct(){parent::__construct();}
        public function __destruct(){parent::__destruct();}
        public function connect(){parent::connect();}

}


namespace _time_suggestion;
use Model;
class Extras_Model extends Model{

        public function __construct(){parent::__construct();}
        public function __destruct(){parent::__destruct();}
        public function connect(){parent::connect();}

}

namespace _environment;
use Model;
class Extras_Model extends Model{

        public function __construct(){parent::__construct();}
        public function __destruct(){parent::__destruct();}
        public function connect(){parent::connect();}

        /**
         * @return array
         * From Postcodes Table
         */
        public function fetchEnvironmentData(){

                $statement = !is_null($this->pars->postcode_id) ? "WHERE zc_id={$this->pars->postcode_id}" : "";

                $sql = "SELECT * FROM zip_coordinates {$statement}";
                $this->connect();
                $this->db->setQuery($sql);
                $data = $this->db->fetch();

                return array(
                        "resulta" => $this->db->resulta,
                        "process" => $this->db->process,
                        "data"    => $data,
                        "sql"     => $this->db->getQueryString(),
                        "errInfo" => $this->db->errInfo,
                        "errCode" => $this->db->errCode
                );

        }



}


namespace _place_covering;
use Model;
class Extras_Model extends Model{

        public function __construct(){parent::__construct();}
        public function __destruct(){parent::__destruct();}
        public function connect(){parent::connect();}

}