<?php
/**
 * Created by PhpStorm.
 * User: suleymantopaloglu
 * Date: 17.12.18
 * Time: 09:25
 */

class FrameworkTest_Model extends Model
{
        public function connect()
        {
                parent::connect(); // TODO: Change the autogenerated stub
        }

}