<?php
/**
 * Created by PhpStorm.
 * User: suleymantopaloglu
 * Date: 05.02.19
 * Time: 14:20
 */

namespace gtc;
use Model;

class Gtc_Model extends Model
{

        public function __construct()
        {
                parent::__construct();
        }

        public function connect()
        {
                parent::connect(); // TODO: Change the autogenerated stub
        }


        public function __destruct()
        {
                parent::__destruct(); // TODO: Change the autogenerated stub
        }


}