<?php
/**
 * Created by PhpStorm.
 * User: suleymantopaloglu
 * Date: 25.09.18
 * Time: 22:17
 */

namespace _start;

use Database;
use Model;
use _list\Meeting_Model as Meetings;

class Home_Model extends Model
{
        public function connect()
        {
                parent::connect(); // TODO: Change the autogenerated stub
        }


        function fetchAllAds()
        {
                $this->connect();

                $this->db->setTable("club_advertisement");
                $this->db->setCondition("club_id", 1, "AND");
                // $this->db->setCondition("status", true);
                $this->db->setCondition("id", 24, "OR");
                $this->db->setCondition("id", 28, "OR");
                $this->db->setCondition("id", 31 );
                $this->db->setSingleValueWithKey(true);
                return $this->db->fetch();

        }

        function fetchNextMeeting(){

                include "Models/Meeting_Model.php";


                // $this->pars->queryCustomStatement = "datum >= NOW() ORDER BY datum ASC LIMIT 1" ;
                $this->pars->queryCustomStatement = "fulldate >= NOW()" ;


                $meetings               = new Meetings();
                $meetings->LIMIT        = 1;
                $meetings->ORDER_BY     = array("datum"=>Database::ORDER_ASC, "id"=>Database::ORDER_ASC );
                $meetings->pars         = $this->pars;

                $data                   = $meetings->fetchAll();

                #highlight_string(var_export($data, true));

                if( count($data) ){
                        return array_shift($data);
                }

                return array();

        }







}