<?php
/**
 * Created by PhpStorm.
 * User: suleymantopaloglu
 * Date: 03.12.18
 * Time: 09:59
 */

namespace manage;
use Model;

class More_Model extends Model
{
        public function __construct()
        {
                parent::__construct();
        }

        public function connect()
        {
                parent::connect(); // TODO: Change the autogenerated stub
        }


}