<?php
/**
 * Created by PhpStorm.
 * User: suleymantopaloglu
 * Date: 30.09.18
 * Time: 18:25
 */
namespace _general;
use Model;
use Database;
use REPOSITORY;
use ACTIVITY;
use ANLASS;
use NOTIFICATION;
use Config;

class Notifications_Model extends Model
{

        public function connect()
        {
                parent::connect();
        }

        function __destruct()
        {
                parent::__destruct(); // TODO: Change the autogenerated stub
        }

        function fetchAll(){




                return array($this->fetchBirthday(), $this->fetchMeeting());
                // return $this->fetchMeeting();




        }



        private function fetchMeeting(){

                $message_prefix         = "Verpasst nicht";
                $my_teams               = REPOSITORY::read(REPOSITORY::CURRENT_USER)["mannschaft"];

                $redirect_url = array("sub_view"=>array(

                        "display_name" => "Settings",
                        "link" => $this->pars->base_url . DIRECTORY_SEPARATOR . "Meeting" . DIRECTORY_SEPARATOR . "_details" . DIRECTORY_SEPARATOR . "index",
                        "icon" => "ic_wrench",
                        "last_check" => "Back link from Team",
                        "unwind_get_data_store"=>"javascript:new Layout().getUnwindDataStore();",
                        // "unwind_action" => "javascript:javascript:unwindAction(); new Meeting().updateAvailability();",
                        ACTIVITY::ACTIVITY=>ACTIVITY::go(ACTIVITY::ACTIVITY_1)

                ),'main_view'=>array());


                $this->connect();
                // $this->db = new Database();
                $sql = "SELECT
                                  id,
                                  (SELECT anls.name FROM anlass as anls WHERE anls.id=t.anlass)                                            AS anlass_name,
                                  (SELECT CONCAT('{$message_prefix}', ' ', CONCAT(UPPER(LEFT(anlass_name, 1)), SUBSTRING(anlass_name, 2))))                             AS m_with_prefix,
                                  (SELECT t.datum)                                                                                    AS m_date,
                                  (SELECT t.beginn)                                                                                   AS m_time,
                                  (SELECT DATE_FORMAT(t.fulldate, '%Y-%m-%d %H:%i:%s'))                                                  AS org_time,
                                  (SELECT TRIM(BOTH '\"' FROM (SELECT JSON_EXTRACT(k.settings, '$.notification_meeting') FROM " . Config::DB_Name . ".kontakt AS k WHERE k.id={$this->pars->uid}))) AS allow,
                                  (SELECT JSON_EXTRACT(k.settings, '$.notification_meeting_plan') FROM " . Config::DB_Name . ".kontakt AS k WHERE k.id={$this->pars->uid}) AS allow_meeting_plan,
                                  (SELECT JSON_EXTRACT(JSON_UNQUOTE(allow_meeting_plan), '$[0]') * 24 * 60 +
                                          JSON_EXTRACT(JSON_UNQUOTE(allow_meeting_plan), '$[1]') * 60 +
                                          JSON_EXTRACT(JSON_UNQUOTE(allow_meeting_plan), '$[2]'))                                     AS minuteinterval,
                                  (SELECT DATE_FORMAT((SELECT DATE_ADD(org_time, INTERVAL -minuteinterval MINUTE)), '%Y-%m-%d %H:%i:%s')) AS notification_time,
                                  (SELECT (SELECT minuteinterval)/60/24 )                                               AS target_time_as_number,
                                  (SELECT NOW()) AS _now,
                                  
                                  /* Notification Title */
                                  (SELECT anlass_name) AS ". NOTIFICATION::X2DataForNotificationTitleKey . ",
                                  
                                  /* Determine Redirect Data as (Index for Tab Or Object for Activity)) */
                                  (SELECT '" . NOTIFICATION::X2DataForNotificationRedirectDataObject . "') AS ". NOTIFICATION::X2DataForNotificationRedirectData . ",
                                  
                                  /* Set Redirect as index based (Open Tab in Main screen) !!!!! this Parameter will be Ignored as top on Top parameter */
                                  (SELECT 2) AS ". NOTIFICATION::X2DataForNotificationRedirectDataIndex . ",
                                         
                                  /* Redirect data as Object Based ( Open And Post Data to Activity )*/
                                  (SELECT REPLACE(
                                                REPLACE(
                                                        REPLACE('" .
                                                                json_encode(
                                                                    array(
                                                                        "display_name" => "replace_anlass_name",
                                                                        "link" => $this->pars->base_url . DIRECTORY_SEPARATOR. "Meeting". DIRECTORY_SEPARATOR . "_details" . DIRECTORY_SEPARATOR . "index/?id=replace_meeting_id",
                                                                        "icon" => "ic_wrench",
                                                                        "unwind_get_data_store"=>"javascript:new Layout().getUnwindDataStore();",
                                                                        // "unwind_action" => "javascript:javascript:unwindAction(); new Meeting().updateAvailability();",
                                                                        ACTIVITY::ACTIVITY=>ACTIVITY::go(ACTIVITY::ACTIVITY_2),
                                                                        "isMatch" => "replace_is_match"
                                                                    )
                                                                )
                                                                . "', 'replace_anlass_name', anlass_name 
                                                                ), 'replace_meeting_id', id 
                                                                ), 'replace_is_match', IF(
                                                                                        (t.anlass=".ANLASS::LIGASPIEL." OR t.anlass=" . ANLASS::POKALSPIEL ." OR t.anlass=".ANLASS::TURNIER." OR t.anlass=".ANLASS::TESTSPIEL . ")
                                                                                        ,'true'
                                                                                        ,'false'
                                                                                        )
                                                                                        )
                                                                                        ) AS ". NOTIFICATION::X2DataForNotificationRedirectDataObject . ",
                                               
                                               
                                               
                                  (SELECT TIMESTAMPDIFF(DAY , NOW(), (SELECT DATE_FORMAT((SELECT DATE_ADD(org_time, INTERVAL -minuteinterval MINUTE)), '%Y-%m-%d %H:%i:%s')))) AS _is_showable,
                                  (SELECT CONCAT(m_with_prefix, ' ', (SELECT (IF(target_time_as_number < 1, CONCAT('Today um ', DATE_FORMAT(t.beginn,'%H:%i')), IF(target_time_as_number < 2, CONCAT('Tomorrow um ', DATE_FORMAT(t.beginn,'%H:%i')), DATE_FORMAT(org_time, 'am %d.%m.%Y um %H:%i'))))))) AS present_day_string
                                
                                FROM termine AS t
                                WHERE 
                                
                                /* IF IN MY TEAM */
                                SOURCE_JSON_IN_SCOOP_JSON('{$my_teams}', t.mannschaft ) AND 
                                
                                /*IF ALLOWED FROM SETTINGS*/
                                (SELECT TRIM(BOTH '\"' FROM (SELECT JSON_EXTRACT(k.settings, '$.notification_meeting') FROM " . Config::DB_Name . ".kontakt AS k WHERE k.id={$this->pars->uid}))) AND (
                                
                                /*IF MEETING NOT PASSED */
                                /*  Butun kodun amaci notication time gecmemisse :) Numkunse bu kadar uzamasin saten untte virtual kolonlarin icinde var */
                                (SELECT TIMESTAMPDIFF( 
                                            MINUTE, 
                                            NOW(), (SELECT DATE_FORMAT(
                                                            (SELECT DATE_ADD(
                                                                  (SELECT DATE_FORMAT( t.fulldate, '%Y-%m-%d %H:%i:%s' )), 
                                                                  INTERVAL -(SELECT JSON_EXTRACT(JSON_UNQUOTE((SELECT JSON_EXTRACT(k.settings, '$.notification_meeting_plan')
                                                                                                      FROM " . Config::DB_Name . ".kontakt AS k
                                                                                                      WHERE k.id =
                                                                                                            {$this->pars->uid}) ), '$[0]') * 24 * 60 +
                                                                           JSON_EXTRACT(JSON_UNQUOTE((SELECT JSON_EXTRACT(k.settings, '$.notification_meeting_plan')
                                                                                                      FROM " . Config::DB_Name . ".kontakt AS k
                                                                                                      WHERE k.id =
                                                                                                            {$this->pars->uid}) ), '$[1]') * 60 + JSON_EXTRACT(JSON_UNQUOTE((SELECT JSON_EXTRACT(k.settings, '$.notification_meeting_plan')
                                                                                                                                                             FROM " . Config::DB_Name . ".kontakt AS k
                                                                                                                                                             WHERE k.id =
                                                                                                                                                                   {$this->pars->uid}) ),
                                                                                                                                                      '$[2]')) MINUTE)),
                             '%Y-%m-%d %H:%i:%s'))  )) > -1 ) ORDER BY
                                          t.fulldate ASC LIMIT {$this->pars->limit}";

                $this->db->setQuery($sql);
                $this->db->setSingleValueWithKey(true);
                $data = $this->db->fetch();
                #highlight_string(var_export($data, true));
                // echo $this->db->getQueryString();
                /*return array(
                    "resulta"=>$this->db->resulta,
                    "process"=>$this->db->process,
                    "data"=>$data,
                    "sql"=>$this->db->getQueryString(),
                    "errCode"=>$this->db->errCode,
                    "errInfo"=>$this->db->errInfo,
                );*/
                return $data;




        }

        private function fetchBirthday(){

                $message_prefix = "Verpasst nicht Geburtstag für";
                $my_teams       = REPOSITORY::read(REPOSITORY::CURRENT_USER)["mannschaft"];
                $my_name        = REPOSITORY::read(REPOSITORY::CURRENT_USER)["final_name"];
                $uid            = REPOSITORY::read(REPOSITORY::CURRENT_USER)["uid"];

                $this->connect();
                // $this->db = new Database(); // ??
                $sql = "SELECT
                          id,
                          (SELECT '$my_name') as my_name,
                          (SELECT '$uid') as my_id,
                          (SELECT k.geburtsdatum) AS birthday,
                          (SELECT MONTH(NOW())) AS current_month,
                                                    /*(SELECT
                             STR_TO_DATE(CONCAT(YEAR(NOW()), '-', MONTH(k.geburtsdatum), '-', DAY(k.geburtsdatum)), '%Y-%m-%d'))     AS birthday,*/
                          (SELECT settings FROM " . Config::DB_Name . ".kontakt WHERE id=$uid)                                                          AS settings,
                          (SELECT TRIM(BOTH '\"' FROM (SELECT JSON_EXTRACT((SELECT settings FROM " . Config::DB_Name . ".kontakt WHERE id=$uid), '$.notification_birthday')))) AS allow,
                          (SELECT JSON_EXTRACT((SELECT settings FROM " . Config::DB_Name . ".kontakt WHERE id=$uid), '$.notification_birthday_plan'))                                            AS allow_birthday_plan,
                          (SELECT JSON_EXTRACT(JSON_UNQUOTE(allow_birthday_plan), '$[0]') * 24 * 60 +
                                  JSON_EXTRACT(JSON_UNQUOTE(allow_birthday_plan), '$[1]') * 60 + JSON_EXTRACT(JSON_UNQUOTE(allow_birthday_plan),
                                                                                                              '$[2]'))                    AS minuteinterval,
                                                                                                              
                           @notification_year := IF(MONTH(k.geburtsdatum) < MONTH(NOW()), YEAR(NOW())+1,YEAR(NOW())) as notification_year,                                                                                   
                                                                                                              
                           (SELECT MAKEDATE(IF(MONTH(k.geburtsdatum) < MONTH(NOW()), YEAR(NOW()) + 1, YEAR(NOW())), DAYOFYEAR(k.geburtsdatum)))  AS target_birthday,                                                                               
                                                                                                              
                                                                                                              
                          (SELECT DATE_FORMAT((SELECT DATE_ADD( target_birthday, INTERVAL -minuteinterval MINUTE)),'%Y-%m-%d %H:%i:%s')) AS notification_time,
                          (SELECT (SELECT minuteinterval) / 60 /
                                  24)                                                                                                     AS target_time_as_number,
                                  
                          /* Notification Title */
                          (SELECT k.final_name) AS ". NOTIFICATION::X2DataForNotificationTitleKey . ",
                                  
                          /* Determine Redirect Data as (Index for Tab Or Object for Activity)) */
                          (SELECT '" . NOTIFICATION::X2DataForNotificationRedirectDataObject . "') AS ". NOTIFICATION::X2DataForNotificationRedirectData . ",
                          
                          /* Set Redirect as index based (Open Tab in Main screen) !!!!! this Parameter will be Ignored as top on Top parameter */
                          (SELECT 2) AS ". NOTIFICATION::X2DataForNotificationRedirectDataIndex . ",
                                 
                          /* Redirect data as Object Based ( Open And Post Data to Activity )*/
                          (SELECT REPLACE(REPLACE('" .
                                json_encode(
                                        array(
                                                "display_name" => "replace_display_name",
                                                "link" => $this->pars->base_url . DIRECTORY_SEPARATOR. "Calendar". DIRECTORY_SEPARATOR . "monthView" . DIRECTORY_SEPARATOR . "index/?id=replace_member_id",
                                                "icon" => "ic_wrench",
                                                "unwind_get_data_store"=>"javascript:new Layout().getUnwindDataStore();",
                                                // "unwind_action" => "javascript:javascript:unwindAction(); new Meeting().updateAvailability();",
                                                ACTIVITY::ACTIVITY=>ACTIVITY::go(ACTIVITY::ACTIVITY_2)
                                        )
                                ) . "', 'replace_display_name', 'Kalendar' ), 'replace_member_id', '0' )
                          ) AS ". NOTIFICATION::X2DataForNotificationRedirectDataObject . ",

                                  
                          (SELECT CONCAT('Verpasst nicht Geburtstag für', ' ', k.final_name, ' ', (SELECT
                                                                             (IF(target_time_as_number < 1, 'Today',
                                                                                 IF(target_time_as_number < 2,
                                                                                    'Tomorrow',
                                                                                    DATE_FORMAT(k.geburtsdatum,
                                                                                                'am %d.%m'))))))) AS present_day_string
                                FROM " . Config::DB_Name . ".kontakt AS k
                                WHERE SOURCE_JSON_IN_SCOOP_JSON('{$my_teams}', (SELECT mannschaft
                                           FROM playerplayed_team_with_season
                                           WHERE 
                                           
                                           player_id = k.id AND season_id = k.current_season)) AND 
                                           
                                           /*IF ALLOWED FROM MEMEBER SETTINGS */
                                           (SELECT TRIM(BOTH '\"' FROM (SELECT JSON_EXTRACT((SELECT settings FROM " . Config::DB_Name . ".kontakt WHERE id=$uid), '$.notification_birthday'))))
                                           
                                           AND (
                                            geburtsdatum IS NOT NULL AND 
          
          
                                                        /*  Butun kodun amaci notication time gecmemisse :)
                                                         Numkunse bu kadar uzamasin saten untte virtual kolonlarin icinde var */
                                                        
                                                        (
        TIMESTAMPDIFF(MINUTE, NOW(), (SELECT DATE_FORMAT((SELECT DATE_ADD(CONCAT((SELECT MAKEDATE(IF(MONTH(k.geburtsdatum) < MONTH(NOW()), YEAR(NOW()) + 1, YEAR(NOW())), DAYOFYEAR(
            k.geburtsdatum))), ' 11:59:00'), INTERVAL -(SELECT JSON_EXTRACT(JSON_UNQUOTE((SELECT JSON_EXTRACT((SELECT settings
                                                                                                               FROM " . Config::DB_Name . ".kontakt
                                                                                                               WHERE id = $uid),
                                                                                                              '$.notification_birthday_plan'))), '$[0]') * 24 * 60 +
                                                               JSON_EXTRACT(JSON_UNQUOTE((SELECT JSON_EXTRACT((SELECT settings
                                                                                                               FROM " . Config::DB_Name . ".kontakt
                                                                                                               WHERE id = $uid),
                                                                                                              '$.notification_birthday_plan'))), '$[1]') * 60 + JSON_EXTRACT(JSON_UNQUOTE((SELECT JSON_EXTRACT((SELECT settings
                                                                                                                                                                                                                FROM " . Config::DB_Name . ".kontakt
                                                                                                                                                                                                                WHERE id = $uid),
                                                                                                                                                                                                               '$.notification_birthday_plan'))),
                                                                                                                                           '$[2]')) MINUTE)),
                                                  '%Y-%m-%d %H:%i:%s'))) > 0



      )
                                                        
                                                        ) ORDER BY (SELECT MAKEDATE(
                                                            IF(MONTH(k.geburtsdatum) < MONTH(NOW()), YEAR(NOW()) + 1, YEAR(NOW())), DAYOFYEAR(k.geburtsdatum))) ASC LIMIT {$this->pars->limit} ";

                $this->db->setQuery($sql);
                $this->db->setSingleValueWithKey(true);
                $data = $this->db->fetch();
                #highlight_string(var_export($data, true));
                #echo $this->db->getQueryString();
                /*return array(
                    "resulta"=>$this->db->resulta,
                    "process"=>$this->db->process,
                    "data"=>$data,
                    "sql"=>$this->db->getQueryString(),
                    "errCode"=>$this->db->errCode,
                    "errInfo"=>$this->db->errInfo,
                );
                // */return $data;


        }


        function __construct()
        {
                parent::__construct();
        }

}

