<?php
/**
 * Created by PhpStorm.
 * User: suleymantopaloglu
 * Date: 31.01.19
 * Time: 13:39
 */

class Sample_Model extends Model
{
        public function __construct()
        {
                parent::connect();
        }

        public function connect()
        {
                parent::connect(); // TODO: Change the autogenerated stub
        }

        function __destruct()
        {
                parent::__destruct(); // TODO: Change the autogenerated stub
        }


}