<?php
/**
 * Created by PhpStorm.
 * User: suleymantopaloglu
 * Date: 25.09.18
 * Time: 22:17
 */

namespace in;
use Model;
use REPOSITORY;
use Helper;
use Database;

class Sign_Model extends Model
{

        /**
         * User_Model constructor.
         */
        public function __construct()
        {
                parent::__construct();
        }

        public function __destruct()
        {
                parent::__destruct(); // TODO: Change the autogenerated stub
        }


        public function connect()
        {
                parent::connect(); // TODO: Change the autogenerated stub
        }

        function fetch()
        {


                include "Models/Contact_Model.php";
                $contact = new \_list\Contact_Model();
                unset($this->pars->output);
                unset($this->pars->with_session);
                $contact->pars = $this->pars;
                $data = $contact->fetchAll();



                #highlight_string(var_export($data, true));
                if (count($data)) {
                        return array_shift($data);
                }

                return null;

        }

        function checkNumber()
        {

                $mobil_number = $this->pars->mobil_number;

                $this->db = new Database();
                $query = "SELECT * FROM kontakt WHERE mobil_number LIKE '%{$mobil_number}' AND LENGTH('{$mobil_number}') >=10;";

                $this->db->setQuery($query);
                // $this->db->setCondition("mobil_number", $this->pars->mobil_number );
                $data = $this->db->fetch();
                // echo $this->db->getQueryString();

                return $data;

        }

        function setNumberActivationCode()
        {
                #highlight_string(var_export($this->pars, true));

                // echo $this->pars->mobil_confirmation_next_try;
                $this->db = new Database();
                $this->db->setTable("kontakt");
                $this->db->set("mobil_confirmation", $this->pars->confirmation_code );
                $this->db->set("mobil_confirmation_next_try", $this->pars->mobil_confirmation_next_try );
                $this->db->setCondition("mobil_number", $this->pars->mobil_number );

                $this->db->Update();

                #echo $this->db->getQueryString();
                return $this->db;

        }


        function fetchClub()
        {

                $this->connect();
                // $this->db = new Database();
                $this->db->setTable("clubs");
                $this->db->setCondition("id", REPOSITORY::read(REPOSITORY::CURRENT_USER)["club_id"]);
                return $this->db->fetch();

        }




}


namespace up;
use Model;
use Database;
use Helper;
use in\Sign_Model as SignInModel;

class Sign_Model extends Model
{

        /**
         * User_Model constructor.
         */
        public function __construct()
        {
                parent::__construct();
        }

        public function __destruct()
        {
                parent::__destruct(); // TODO: Change the autogenerated stub
        }


        public function connect()
        {
                parent::connect(); // TODO: Change the autogenerated stub
        }


        public function save()
        {



                #highlight_string(var_export($this->pars, true));

                $this->db = new Database();
                $this->db->setTable("kontakt");
                $this->db->set("nachname", $this->pars->nachname);
                $this->db->set("vorname", $this->pars->vorname);
                $this->db->set("teamrolle ", $this->pars->teamrolle );
                $this->db->set("mobil_number", $this->pars->mobil_number);
                $this->db->set("mobil_confirmation_next_try", $this->pars->mobil_confirmation_next_try);
                $this->db->set("team", NULL);
                $this->db->set("club_id", NULL);
                $this->db->set("mobil_confirmation", $this->pars->confirmation_code );
                $this->db->Insert();

                /*$this->db->extras = array(
                        "confirmation_code" => $confirmation_code,
                        "mobil_number" => $mobil_number
                );*/

                return $this->db;





        }

}


namespace confirmation;
use Model;
use Database;


class Sign_Model extends Model
{

        /**
         * User_Model constructor.
         */
        public function __construct()
        {
                parent::__construct();
        }

        public function __destruct()
        {
                parent::__destruct(); // TODO: Change the autogenerated stub
        }


        public function connect()
        {
                parent::connect(); // TODO: Change the autogenerated stub
        }

        public function check()
        {

                $this->db = new Database();
                $this->db->setTable("kontakt");
                $this->db->set("mobil_confirmation", NULL);
                // $this->db->set("mobil_confirmation_next_try", NULL);
                $this->db->setCondition("mobil_number", $this->pars->mobil_number ,"AND" );
                $this->db->setCondition("mobil_confirmation", $this->pars->mobil_confirmation );
                $data = $this->db->fetch();

                // $this->db->process = true;
                // $this->db->resulta = true;
                $this->db->extras = $data;


                return $this->db;






        }

        public function save()
        {

                $this->db = new Database();
                $this->db->setTable("kontakt");
                $this->db->set("mobil_confirmation", NULL);
                // $this->db->set("mobil_confirmation_next_try", NULL);
                $this->db->setCondition("mobil_number", $this->pars->mobil_number ,"AND" );
                $this->db->setCondition("mobil_confirmation", $this->pars->mobil_confirmation );
                $this->db->Update();

                // $this->db->process = true;
                // $this->db->resulta = true;


                return $this->db;






        }


}

namespace newPassword;

use Model;
use Database;
use in\Sign_Model as SignIn;

class Sign_Model extends Model{

        public function __construct()
        {
                parent::__construct();
        }

        public function connect()
        {
                parent::connect(); // TODO: Change the autogenerated stub
        }

        function __destruct()
        {
                parent::__destruct(); // TODO: Change the autogenerated stub
        }


        function request()
        {

                $signIn = new SignIn();
                $signIn->pars = $this->pars;
                return $signIn->checkNumber();

        }


        function setNumberActivationCode()
        {

                #highlight_string(var_export($this->pars, true));
                $this->db = new Database();
                $this->db->setTable("kontakt");
                $this->db->set("mobil_confirmation", $this->pars->confirmation_code );
                $this->db->set("mobil_confirmation_next_try", $this->pars->mobil_confirmation_next_try );
                $this->db->setCondition("mobil_number", $this->pars->mobil_number );

                $this->db->Update();

                // echo $this->db->getQueryString();
                return $this->db;

        }

        public function save()
        {


                // echo $this->pars->mobil_confirmation_next_try;
                $this->db = new Database();
                $this->db->setTable("kontakt");
                $this->db->set("password", $this->pars->password );
                $this->db->setCondition("mobil_number", $this->pars->mobil_number );

                $this->db->Update();
                return $this->db;







        }


}


