<?php
/**
 * Created by PhpStorm.
 * User: suleymantopaloglu
 * Date: 2019-06-17
 * Time: 17:12
 */

class TeamsCard_Model extends Model
{
        public function __construct()
        {
                parent::__construct();
        }

        public function connect()
        {
                parent::connect(); // TODO: Change the autogenerated stub
        }

        static function Entity()
        {
                return parent::Entity(); // TODO: Change the autogenerated stub
        }

        function __destruct()
        {
                parent::__destruct(); // TODO: Change the autogenerated stub
        }

        function fetchUserUsingRoleById(){


                #highlight_string(var_export($this->pars, true));

                $sql = "SELECT * FROM user_using_roles WHERE id=" . intval($this->pars->role_id);

                $this->db = new Database();
                $this->db->setQuery($sql);
                $data =  $this->db->fetch();
                #echo $this->db->getQueryString();


                return $data;


        }


        function fetchPrettyCellDataFromVirtualDatabase(){

                // highlight_string(var_export($this->pars, true));
                $uniqueID = uniqid();
                $sql = "SELECT 
                        (SELECT FLOOR(1+RAND()*60)) as id,
                        (SELECT teamName2 FROM dfb.dfb_league_clubs WHERE id=" . $this->pars->club_id . ") as pretty_club_name,
                        (SELECT name FROM club_teams_pool WHERE id=" . $this->pars->team_id . ") as pretty_team_name,
                        (SELECT name FROM sub_teams WHERE id=" . $this->pars->team_group_id . ") as pretty_team_group_name,
                        (SELECT name FROM leagues WHERE id=" . $this->pars->league_id . ") as pretty_league_name,
                        (SELECT CONCAT(vorname, ' ', nachname) FROM kontakt WHERE id=" . $this->pars->trainer_id . ") as pretty_trainer_name
                ";

                $this->db = new Database();
                $this->db->setQuery($sql);
                $this->db->setSingleValueWithKey(true);
                return $this->db->fetch();





        }



}