<?php
/**
 * Created by PhpStorm.
 * User: suleymantopaloglu
 * Date: 16.02.19
 * Time: 04:02
 */

namespace tableView;
use Model;

class Test_Model extends Model
{
        function __construct() {
                parent::__construct();
        }

        function __destruct()
        {
                parent::__destruct(); // TODO: Change the autogenerated stub
        }

        public function connect()
        {
                parent::connect(); // TODO: Change the autogenerated stub
        }


}